source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'Your-Day' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  # Pods for Your-Day

end
